name: Check if Goa can generate a design
on: [push]
jobs:
  goa-generate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: install Protoc
      uses: arduino/setup-protoc@v1 
    - name: install Goa
      run: make install-goa
    - name: generate Goa design
      run: make generate
    - name: everything builds
      run: go build ./...
        